# Generated by Django 3.0.5 on 2020-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='username',
            field=models.CharField(default='test@gmail.com', max_length=100),
        ),
    ]
