# Generated by Django 3.0.5 on 2020-05-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherData', '0002_city_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
